desc 'Running find_term_html cucumber'
task :run_html_features do
  sh 'cucumber features/find_term_html/'
end

desc 'Running find_term_html cucumber'
task :run_json_features do
  sh 'cucumber features/find_term_json/'
end

require 'parallel_tests/tasks'
require 'rspec/core/rake_task'

namespace :spec do
  desc 'Run all specs'
  RSpec::Core::RakeTask.new(:all) do |task|
    task.pattern = 'spec/**/*_spec.rb'
  end

  desc 'Run all specs in 4 parallel processes'
  task :parallel do
    sh 'parallel_rspec -n 4'
  end

  desc 'Run specs in spec/find_term_html'
  RSpec::Core::RakeTask.new(:html) do |task|
    task.pattern = 'spec/find_term_html/**/*_spec.rb'
  end

  desc 'Run specs in spec/find_term_json'
  RSpec::Core::RakeTask.new(:json) do |task|
    task.pattern = 'spec/find_term_json/**/*_spec.rb'
  end
end

task default: 'spec:all'

